// Generated by gencpp from file realsense_demo/ExecuteTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORYRESPONSE_H
#define REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_demo
{
template <class ContainerAllocator>
struct ExecuteTrajectoryResponse_
{
  typedef ExecuteTrajectoryResponse_<ContainerAllocator> Type;

  ExecuteTrajectoryResponse_()
    : result(false)  {
    }
  ExecuteTrajectoryResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteTrajectoryResponse_

typedef ::realsense_demo::ExecuteTrajectoryResponse_<std::allocator<void> > ExecuteTrajectoryResponse;

typedef boost::shared_ptr< ::realsense_demo::ExecuteTrajectoryResponse > ExecuteTrajectoryResponsePtr;
typedef boost::shared_ptr< ::realsense_demo::ExecuteTrajectoryResponse const> ExecuteTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator1> & lhs, const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator1> & lhs, const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_demo/ExecuteTrajectoryResponse";
  }

  static const char* value(const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_demo::ExecuteTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORYRESPONSE_H
