// Generated by gencpp from file realsense_demo/ExecuteTrajectory.msg
// DO NOT EDIT!


#ifndef REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORY_H
#define REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORY_H

#include <ros/service_traits.h>


#include <realsense_demo/ExecuteTrajectoryRequest.h>
#include <realsense_demo/ExecuteTrajectoryResponse.h>


namespace realsense_demo
{

struct ExecuteTrajectory
{

typedef ExecuteTrajectoryRequest Request;
typedef ExecuteTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteTrajectory
} // namespace realsense_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_demo::ExecuteTrajectory > {
  static const char* value()
  {
    return "36a44f45282f917780a89bd95d2a9827";
  }

  static const char* value(const ::realsense_demo::ExecuteTrajectory&) { return value(); }
};

template<>
struct DataType< ::realsense_demo::ExecuteTrajectory > {
  static const char* value()
  {
    return "realsense_demo/ExecuteTrajectory";
  }

  static const char* value(const ::realsense_demo::ExecuteTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_demo::ExecuteTrajectoryRequest> should match
// service_traits::MD5Sum< ::realsense_demo::ExecuteTrajectory >
template<>
struct MD5Sum< ::realsense_demo::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_demo::ExecuteTrajectory >::value();
  }
  static const char* value(const ::realsense_demo::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_demo::ExecuteTrajectoryRequest> should match
// service_traits::DataType< ::realsense_demo::ExecuteTrajectory >
template<>
struct DataType< ::realsense_demo::ExecuteTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_demo::ExecuteTrajectory >::value();
  }
  static const char* value(const ::realsense_demo::ExecuteTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_demo::ExecuteTrajectoryResponse> should match
// service_traits::MD5Sum< ::realsense_demo::ExecuteTrajectory >
template<>
struct MD5Sum< ::realsense_demo::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_demo::ExecuteTrajectory >::value();
  }
  static const char* value(const ::realsense_demo::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_demo::ExecuteTrajectoryResponse> should match
// service_traits::DataType< ::realsense_demo::ExecuteTrajectory >
template<>
struct DataType< ::realsense_demo::ExecuteTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_demo::ExecuteTrajectory >::value();
  }
  static const char* value(const ::realsense_demo::ExecuteTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_DEMO_MESSAGE_EXECUTETRAJECTORY_H
